### ISSUE TITLE
Enable use of portal-provided file pickers

### ISSUE THREAD

**Issue by ssokolow** [flathub/com.github.libresprite.LibreSprite#11]
Judging by [this line](https://github.com/LibreSprite/LibreSprite/blob/8a77f5a55213202a346e70088c4548b07afd5ed6/src/she/common/system.h#L15) of the source, LibreSprite has a GTK backend for its `Preferences > Experimental > Use native file dialog` checkbox, but nothing appears to change in the Flatpak build when that checkbox is checked.

My first guess would be that the Flatpak build configuration results in the `ASEPRITE_WITH_GTK_FILE_DIALOG_SUPPORT` define not being set.

**Comment by Alexander-Wilms** [comment]
Looks like that option will be removed: https://github.com/LibreSprite/LibreSprite/pull/237

**Comment by ssokolow** [comment]
I raised the issue with them and LibreSprite/LibreSprite#242 has been opened to track fixing and stabilizing the functionality.
